# frozen_string_literal: true

require 'rails_helper'
require_relative '../../../app/lib/google_drive/gDrive.rb'

# RSpec.describe Image do
describe 'Image' do
  xit 'returns the correct formated data from google drive' do
    data = File.read('./spec/fixtures/google_drive_data.json')
    google_drive_response = JSON.parse(data)
    allow(GoogleDrive::Session)
      .to receive(:from_service_account_key)
      .and_return(google_drive_response)

    images = Image.images
    expect(images).to eq(false)
  end
end
# end

# [{:id=>"1y7MHIl8cfQ_KiC2I4Pj5JzzbUBCzACPh",
#   :kind=>"drive#file",
#   :name=>"hello.txt",
#   :mimeType=>"text/plain",
#   :webViewLink=>"https://drive.google.com/file/d/1y7MHIl8cfQ_KiC2I4Pj5JzzbUBCzACPh/view?usp=drivesdk",
#   :webContentLink=>"https://drive.google.com/uc?id=1y7MHIl8cfQ_KiC2I4Pj5JzzbUBCzACPh&export=download",
#   :parents=>["0AEfdR0PXAVRjUk9PVA"]},
#  {:id=>"1nZpra-CACofMfuwpiSUk4yroK2OGJ2hY",
#   :kind=>"drive#file",
#   :name=>"hello.txt",
#   :mimeType=>"text/plain",
#   :webViewLink=>"https://drive.google.com/file/d/1nZpra-CACofMfuwpiSUk4yroK2OGJ2hY/view?usp=drivesdk",
#   :webContentLink=>"https://drive.google.com/uc?id=1nZpra-CACofMfuwpiSUk4yroK2OGJ2hY&export=download",
#   :parents=>["0AEfdR0PXAVRjUk9PVA"]},
#  {:id=>"12rdzMSISqNElybgGQdMIL6WP2oU4KO3c",
#   :kind=>"drive#file",
#   :name=>"video",
#   :mimeType=>"application/vnd.google-apps.folder",
#   :webViewLink=>"https://drive.google.com/drive/folders/12rdzMSISqNElybgGQdMIL6WP2oU4KO3c",
#   :webContentLink=>nil,
#   :parents=>["1jNExVIifVofhi-w_9s2ejTEaaVDl7csE"]},
#  {:id=>"1XIrGEf6qUadMdbebjxkPQsOQFY2OkWJC",
#   :kind=>"drive#file",
#   :name=>"carousel",
#   :mimeType=>"application/vnd.google-apps.folder",
#   :webViewLink=>"https://drive.google.com/drive/folders/1XIrGEf6qUadMdbebjxkPQsOQFY2OkWJC",
#   :webContentLink=>nil,
#   :parents=>["1jNExVIifVofhi-w_9s2ejTEaaVDl7csE"]},
#  {:id=>"1wCVR2jhPT-ZbfLSuCLanLfbOR6HplMC9",
#   :kind=>"drive#file",
#   :name=>"troy-diving.jpg",
#   :mimeType=>"image/jpeg",
#   :webViewLink=>"https://drive.google.com/file/d/1wCVR2jhPT-ZbfLSuCLanLfbOR6HplMC9/view?usp=drivesdk",
#   :webContentLink=>"https://drive.google.com/uc?id=1wCVR2jhPT-ZbfLSuCLanLfbOR6HplMC9&export=download",
#   :parents=>["1XIrGEf6qUadMdbebjxkPQsOQFY2OkWJC"]},
#  {:id=>"1S6uQZ_CxWKJP8cJIP1A2IoxPHexEgFCd",
#   :kind=>"drive#file",
#   :name=>"wine.jpeg",
#   :mimeType=>"image/jpeg",
#   :webViewLink=>"https://drive.google.com/file/d/1S6uQZ_CxWKJP8cJIP1A2IoxPHexEgFCd/view?usp=drivesdk",
#   :webContentLink=>"https://drive.google.com/uc?id=1S6uQZ_CxWKJP8cJIP1A2IoxPHexEgFCd&export=download",
#   :parents=>["1XIrGEf6qUadMdbebjxkPQsOQFY2OkWJC"]},
#  {:id=>"1fwtqwmPR81wI6hHlHPqRpcW-o6daAPlo",
#   :kind=>"drive#file",
#   :name=>"gallery",
#   :mimeType=>"application/vnd.google-apps.folder",
#   :webViewLink=>"https://drive.google.com/drive/folders/1fwtqwmPR81wI6hHlHPqRpcW-o6daAPlo",
#   :webContentLink=>nil,
#   :parents=>["1jNExVIifVofhi-w_9s2ejTEaaVDl7csE"]},
#  {:id=>"1jNExVIifVofhi-w_9s2ejTEaaVDl7csE",
#   :kind=>"drive#file",
#   :name=>"app_pictures",
#   :mimeType=>"application/vnd.google-apps.folder",
#   :webViewLink=>"https://drive.google.com/drive/folders/1jNExVIifVofhi-w_9s2ejTEaaVDl7csE",
#   :webContentLink=>nil,
#   :parents=>nil},
#  {:id=>"11XBCEl7Fg-3HZE1lyJ5U82RSBgQOrZn5",
#   :kind=>"drive#file",
#   :name=>"img_2.jpg",
#   :mimeType=>"image/jpeg",
#   :webViewLink=>"https://drive.google.com/file/d/11XBCEl7Fg-3HZE1lyJ5U82RSBgQOrZn5/view?usp=drivesdk",
#   :webContentLink=>"https://drive.google.com/uc?id=11XBCEl7Fg-3HZE1lyJ5U82RSBgQOrZn5&export=download",
#   :parents=>["1fwtqwmPR81wI6hHlHPqRpcW-o6daAPlo"]},
#  {:id=>"185Mf78Eh-BhUSBMG1iCEcgzF7kpXJFbA",
#   :kind=>"drive#file",
#   :name=>"milo.jpg",
#   :mimeType=>"image/jpeg",
#   :webViewLink=>"https://drive.google.com/file/d/185Mf78Eh-BhUSBMG1iCEcgzF7kpXJFbA/view?usp=drivesdk",
#   :webContentLink=>"https://drive.google.com/uc?id=185Mf78Eh-BhUSBMG1iCEcgzF7kpXJFbA&export=download",
#   :parents=>["1XIrGEf6qUadMdbebjxkPQsOQFY2OkWJC"]},
#  {:id=>"163BayE4emhG8YxMo9RQ7df50-SyHIOR5",
#   :kind=>"drive#file",
#   :name=>"fs-01.jpg",
#   :mimeType=>"image/jpeg",
#   :webViewLink=>"https://drive.google.com/file/d/163BayE4emhG8YxMo9RQ7df50-SyHIOR5/view?usp=drivesdk",
#   :webContentLink=>"https://drive.google.com/uc?id=163BayE4emhG8YxMo9RQ7df50-SyHIOR5&export=download",
#   :parents=>["1XIrGEf6qUadMdbebjxkPQsOQFY2OkWJC"]},
#  {:id=>"1p5XpxxbBQr49Hmcc5MXhwKXK-BH9i7UE",
#   :kind=>"drive#file",
#   :name=>"cool-keybd.jpg",
#   :mimeType=>"image/jpeg",
#   :webViewLink=>"https://drive.google.com/file/d/1p5XpxxbBQr49Hmcc5MXhwKXK-BH9i7UE/view?usp=drivesdk",
#   :webContentLink=>"https://drive.google.com/uc?id=1p5XpxxbBQr49Hmcc5MXhwKXK-BH9i7UE&export=download",
#   :parents=>["1fwtqwmPR81wI6hHlHPqRpcW-o6daAPlo"]},
#  {:id=>"1GpComCIosgGS5hvm3bbH_4emjJ2Dzt6J",
#   :kind=>"drive#file",
#   :name=>"img_3.jpg",
#   :mimeType=>"image/jpeg",
#   :webViewLink=>"https://drive.google.com/file/d/1GpComCIosgGS5hvm3bbH_4emjJ2Dzt6J/view?usp=drivesdk",
#   :webContentLink=>"https://drive.google.com/uc?id=1GpComCIosgGS5hvm3bbH_4emjJ2Dzt6J&export=download",
#   :parents=>["1fwtqwmPR81wI6hHlHPqRpcW-o6daAPlo"]},
#  {:id=>"1WqD_xQG4cHuqYM5bgrmLJaC8i_0R-Mc-",
#   :kind=>"drive#file",
#   :name=>"img_6.JPG",
#   :mimeType=>"image/jpeg",
#   :webViewLink=>"https://drive.google.com/file/d/1WqD_xQG4cHuqYM5bgrmLJaC8i_0R-Mc-/view?usp=drivesdk",
#   :webContentLink=>"https://drive.google.com/uc?id=1WqD_xQG4cHuqYM5bgrmLJaC8i_0R-Mc-&export=download",
#   :parents=>["1fwtqwmPR81wI6hHlHPqRpcW-o6daAPlo"]},
#  {:id=>"1SsknxV5Dv86nWdi5Zrm7ucgX_S5MPO7Z",
#   :kind=>"drive#file",
#   :name=>"GOPR0161.MP4",
#   :mimeType=>"video/mp4",
#   :webViewLink=>"https://drive.google.com/file/d/1SsknxV5Dv86nWdi5Zrm7ucgX_S5MPO7Z/view?usp=drivesdk",
#   :webContentLink=>"https://drive.google.com/uc?id=1SsknxV5Dv86nWdi5Zrm7ucgX_S5MPO7Z&export=download",
#   :parents=>["12rdzMSISqNElybgGQdMIL6WP2oU4KO3c"]},
#  {:id=>"1PpC6sQl-vqEF0IhSiaByu4kRvFI9whZL",
#   :kind=>"drive#file",
#   :name=>"img_4.JPG",
#   :mimeType=>"image/jpeg",
#   :webViewLink=>"https://drive.google.com/file/d/1PpC6sQl-vqEF0IhSiaByu4kRvFI9whZL/view?usp=drivesdk",
#   :webContentLink=>"https://drive.google.com/uc?id=1PpC6sQl-vqEF0IhSiaByu4kRvFI9whZL&export=download",
#   :parents=>["1fwtqwmPR81wI6hHlHPqRpcW-o6daAPlo"]}]
